version: "3"
services:
  backend:
    image: alexdobrushskiy/tt_backend:0.1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
  frontend:
    image: alexdobrushskiy/tt_frontend:0.1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "9000:9000"
    networks:
      - webnet
networks:
  webnet: