# Generated by Django 2.1.5 on 2019-01-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[('User', 0), ('Manager', 1), ('Admin', 2)], default=0),
        ),
    ]
