# Generated by Django 2.1.5 on 2019-01-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_caloriesperday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
