# Generated by Django 2.1.5 on 2019-02-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190128_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.PositiveIntegerField(),
        ),
    ]
