# Generated by Django 2.1.5 on 2019-01-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Manager'), (2, 'Admin')], default=0),
        ),
    ]
