export const OPEN_REGISTER_FORM = 'OPEN_REGISTER_FORM';
export const CLOSE_REGISTER_FORM = 'CLOSE_REGISTER_FORM';
export const SAVE_API_TOKEN = 'SAVE_API_TOKEN';
export const FORGET_API_TOKEN = 'FORGET_API_TOKEN';
