export const OPEN_REGISTER_FORM = 'OPEN_REGISTER_FORM';
export const CLOSE_REGISTER_FORM = 'CLOSE_REGISTER_FORM';
export const SAVE_API_TOKEN = 'SAVE_API_TOKEN';
export const FORGET_API_TOKEN = 'FORGET_API_TOKEN';
export const SAVE_MEAL_LIST = 'SAVE_MEAL_LIST';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_MAX_PAGE = 'SET_MAX_PAGE';
export const SET_FILTER_FIELD = 'SET_FILTER_FIELD';
